target("app.framework.qt-transport")
    set_kind("static")
    add_rules("qt.static")
    add_deps("app.framework.bridge", {public = true})
    add_deps("app.framework.bridge-registry", {public = true})
    add_deps("app.framework.app-lifecycle", {public = true})
    add_files("src/*.cpp", "include/**.hpp")
    add_includedirs("include", {public = true})
    add_frameworks("QtCore", "QtNetwork", "QtWebSockets", {public = true})
    add_packages("def_type", {public = true})

target("test-bridge-channel-adapter")
    set_kind("binary")
    set_default(false)
    add_rules("qt.console")
    add_deps("app.framework.qt-transport")
    add_files("tests/unit/bridge_channel_adapter_test.cpp")
    add_frameworks("QtCore", "QtTest")
    add_packages("catch2")
    set_rundir("$(projectdir)")
