target("qt-bridges")
    set_kind("static")
    add_rules("qt.static")
    add_files("src/*.cpp", "include/**.hpp")
    add_includedirs("include", {public = true})
    add_deps("todos-bridge")
    add_frameworks("QtCore", "QtGui", "QtWidgets", {public = true})
