-- Capture globals at parse time so before_build closures can access them
local _APP_NAME    = APP_NAME
local _APP_SLUG    = APP_SLUG
local _APP_VERSION = APP_VERSION

target("desktop")
    set_kind("binary")
    add_rules("qt.widgetapp")
    add_deps("todo-bridge", "web-shell")
    add_files(
        "src/main.cpp",
        "resources/resources.qrc",
        "web_dist_resources.cpp"
    )
    if is_plat("windows") then
        set_filename(APP_NAME .. ".exe")
        add_files("resources/app.rc")
    elseif is_plat("macosx") then
        set_filename(APP_NAME)
    else
        set_filename(APP_SLUG)
    end
    add_frameworks(
        "QtWidgets", "QtGui",
        "QtWebEngineCore", "QtWebEngineWidgets", "QtWebChannel"
    )
    add_defines('APP_NAME="' .. APP_NAME:gsub('"', '\\"') .. '"')
    add_defines('APP_SLUG="' .. APP_SLUG:gsub('"', '\\"') .. '"')
    add_defines('APP_VERSION="' .. APP_VERSION:gsub('"', '\\"') .. '"')

    before_build(function(target)
        local base = os.scriptdir()
        local project_root = os.projectdir()
        local web_dir = path.join(project_root, "web")
        local dist_dir = path.join(web_dir, "dist")

        -- Pass APP_NAME to Vite so index.html and React can use it
        os.setenv("VITE_APP_NAME", _APP_NAME)

        -- 1. Build the web app (skip if sources haven't changed)
        local stamp_file = path.join(project_root, "build", ".web-build-stamp")
        local src_dir = path.join(web_dir, "src")
        local needs_build = not os.isdir(dist_dir) or not os.isfile(stamp_file)
        if not needs_build then
            local stamp_mtime = os.mtime(stamp_file)
            for _, f in ipairs(os.files(path.join(src_dir, "**"))) do
                if os.mtime(f) > stamp_mtime then needs_build = true; break end
            end
            -- Also check index.html and package.json
            for _, f in ipairs({path.join(web_dir, "index.html"), path.join(web_dir, "package.json")}) do
                if os.isfile(f) and os.mtime(f) > stamp_mtime then needs_build = true; break end
            end
        end
        if needs_build then
            os.execv("bun", {"install"}, {curdir = web_dir})
            os.execv("bun", {"run", "build"}, {curdir = web_dir})
            io.writefile(stamp_file, os.date())
        else
            print("Web build is up to date — skipping.")
        end

        -- 2. Generate a .qrc listing every file in dist/
        local qrc_lines = {'<RCC>', '    <qresource prefix="/web">'}
        for _, f in ipairs(os.files(path.join(dist_dir, "**"))) do
            local rel = path.relative(f, dist_dir):gsub("\\", "/")
            local abs = path.absolute(f):gsub("\\", "/")
            table.insert(qrc_lines, '        <file alias="' .. rel .. '">' .. abs .. '</file>')
        end
        table.insert(qrc_lines, '    </qresource>')
        table.insert(qrc_lines, '</RCC>')

        local qrc_path = path.join(base, "web_dist.qrc")
        io.writefile(qrc_path, table.concat(qrc_lines, "\n") .. "\n")

        -- 3. Compile the .qrc into a .cpp via rcc
        --    Windows: bin/rcc.exe    macOS/Linux: libexec/rcc (since Qt 6.1)
        local qt_dir = target:data("qt.dir") or get_config("qt")
        local rcc
        if is_host("windows") then
            rcc = path.join(qt_dir, "bin", "rcc.exe")
        else
            rcc = path.join(qt_dir, "libexec", "rcc")
            if not os.isfile(rcc) then
                rcc = path.join(qt_dir, "bin", "rcc")
            end
        end
        local cpp_path = path.join(base, "web_dist_resources.cpp")
        os.runv(rcc, {"-o", cpp_path, qrc_path})

        -- 4. Generate Windows resource file (app.rc) from APP_NAME/APP_SLUG
        if is_plat("windows") then
            local version = _APP_VERSION
            local version_parts = version:split("%.")
            local v1 = version_parts[1] or "0"
            local v2 = version_parts[2] or "0"
            local v3 = version_parts[3] or "0"
            local rc_content = '// Auto-generated by xmake — do not edit manually\n'
                .. '#include <windows.h>\n\n'
                .. 'IDI_ICON1 ICON "icon.ico"\n\n'
                .. 'VS_VERSION_INFO VERSIONINFO\n'
                .. '    FILEVERSION    ' .. v1 .. ',' .. v2 .. ',' .. v3 .. ',0\n'
                .. '    PRODUCTVERSION ' .. v1 .. ',' .. v2 .. ',' .. v3 .. ',0\n'
                .. '    FILEFLAGSMASK  VS_FFI_FILEFLAGSMASK\n'
                .. '    FILEFLAGS      0\n'
                .. '    FILEOS         VOS_NT_WINDOWS32\n'
                .. '    FILETYPE       VFT_APP\n'
                .. '    FILESUBTYPE    VFT2_UNKNOWN\n'
                .. 'BEGIN\n'
                .. '    BLOCK "StringFileInfo"\n'
                .. '    BEGIN\n'
                .. '        BLOCK "040904B0"\n'
                .. '        BEGIN\n'
                .. '            VALUE "FileDescription",  "' .. _APP_NAME .. '"\n'
                .. '            VALUE "FileVersion",      "' .. version .. '"\n'
                .. '            VALUE "InternalName",     "' .. _APP_SLUG .. '"\n'
                .. '            VALUE "OriginalFilename", "' .. _APP_NAME .. '.exe"\n'
                .. '            VALUE "ProductName",      "' .. _APP_NAME .. '"\n'
                .. '            VALUE "ProductVersion",   "' .. version .. '"\n'
                .. '        END\n'
                .. '    END\n'
                .. '    BLOCK "VarFileInfo"\n'
                .. '    BEGIN\n'
                .. '        VALUE "Translation", 0x0409, 0x04B0\n'
                .. '    END\n'
                .. 'END\n'
            io.writefile(path.join(base, "resources", "app.rc"), rc_content)
        end
    end)

    -- Write the binary path so Playwright desktop tests can find and launch it.
    after_build(function(target)
        io.writefile(path.join(os.projectdir(), "build", ".desktop-binary.txt"), target:targetfile())
    end)
